[display]
default_crs = "auto"
dpi_aware = true

[cache]
dir = "cache"
max_size_mb = 512

[font]
file = "fonts/LXGW.ttf"

[log]
level = "debug"

[vt]
auto_build = true
threshold_verts = 10000000
level_step = 2

